# Generated by Django 3.0.6 on 2020-06-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=214, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('max_time', models.PositiveIntegerField(verbose_name='Max amount of time to spend')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=214, verbose_name='Title')),
                ('is_sequence', models.BooleanField(default=False, verbose_name='Is sequence')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.Exam', verbose_name='Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='exam.Question', verbose_name='Sequence Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.PositiveIntegerField(verbose_name='Time spent')),
                ('base_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='exam.Exam', verbose_name='User Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=214, verbose_name='Title')),
                ('number_in_seq', models.PositiveIntegerField(verbose_name='Number in sequence')),
                ('base_question', models.ManyToManyField(related_name='responses', to='exam.Sequence', verbose_name='Sequence Question')),
                ('user_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='exam.UserExam', verbose_name='UserExam')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=214, verbose_name='Title')),
                ('number_in_seq', models.PositiveIntegerField(verbose_name='Number in sequence')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.Sequence', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.PositiveIntegerField(verbose_name='Choice answer')),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam.Choice', verbose_name='Choice Question')),
                ('user_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.UserExam', verbose_name='UserExam')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=214, verbose_name='Title')),
                ('is_correct', models.BooleanField(verbose_name='Is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.Choice', verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='base_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='exam.Question', verbose_name='Choice Question'),
        ),
    ]
